# Generated by Django 4.2 on 2023-05-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='prices',
            field=models.FloatField(),
        ),
    ]
