# Generated by Django 4.2 on 2023-05-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_alter_realestate_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='descriptions',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='highrespath',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='lowrespath',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='medrespath',
            field=models.CharField(max_length=10000),
        ),
    ]
